manipulation:
  episode: 10000
  random: 200
inference:
  img_height: 752
  img_width: 480
  size_original_cropped: 250
  size_output: 32
  size_cropped: 150
  reward_g_shape: 60
train:
  epoch: 50
  train_batch_size: 512
  validation_batch_size: 512
  percent_validation_set: 0.2